-- GUEST Table Create SQL
CREATE TABLE PROJECTINFO
(
    P_NUM        NUMBER            NOT NULL,
    P_PLAN       VARCHAR2(3000)    NULL, 
    P_NAME       VARCHAR2(100)     NULL, 
    P_CONTENT    VARCHAR2(3000)    NULL, 
    uploadFile   BLOB               NULL,
    P_PERSON     VARCHAR2(100)     NULL, 
    P_DEALINE    VARCHAR2(100)     NULL, 
    P_ORDERS     VARCHAR2(100)     NULL, 
    P_COUNTRY    VARCHAR2(100)     NULL, 
    P_TOTAL      VARCHAR2(1000)    NULL, 
    P_STAT       VARCHAR2(200)     NULL, 
    CONSTRAINT PROJECT_PK PRIMARY KEY (P_NUM)
)
/
CREATE SEQUENCE PROJECTINFO_SEQ
START WITH 1
INCREMENT BY 1;
-- GUEST Table Create SQL
CREATE TABLE FILEINFO
(
    F_NO         NUMBER          NOT NULL, 
    P_NUM        NUMBER          NULL, 
    ORG_NAME     VARCHAR2(20)    NULL, 
    SAV_NAME     VARCHAR2(20)    NULL, 
    F_REGDATE    DATE            NULL, 
    FILE_SIZE    CLOB            NULL, 
    DEL_GB       VARCHAR2(1)     NULL, 
    CONSTRAINT FILEINFO_PK PRIMARY KEY (F_NO),
    CONSTRAINT PROJECT_FK FOREIGN KEY (P_NUM) REFERENCES PROJECTINFO(P_NUM)
       
)
/
CREATE SEQUENCE FILEINFO_SEQ
START WITH 1
INCREMENT BY 1;
/
COMMIT;