/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.22
 * Generated at: 2020-09-22 09:52:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class notice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/./common/include/header.jsp", Long.valueOf(1600761106511L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <!-- font-family: 'Montserrat', sans-serif; -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,500i,600,600i,700\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR:100,300,400,500,700,900&subset=korean\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./common/css/reset.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./common/css/common.css\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- js -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"./common/js/common.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./common/css/notice.css\">\r\n");
      out.write("    \r\n");
      out.write("    <title>withWork</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<!-- font-family: 'Montserrat', sans-serif; -->\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,500i,600,600i,700\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR:100,300,400,500,700,900&subset=korean\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("\r\n");
      out.write("    <!-- css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./common/css/reset.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./common/css/common.css\" />\r\n");
      out.write("    <!-- js -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"./common/js/common.js\"></script>\r\n");
      out.write("    <script src=\"./common/js/work.js\"></script>\r\n");
      out.write("<title>WithWork</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<header>\r\n");
      out.write("      <dl class=\"groupInfo headerInner\">\r\n");
      out.write("          <dt>GOOGLE</dt>\r\n");
      out.write("          <dd>\r\n");
      out.write("              <img src=\"img/user.png\" alt=\"\">\r\n");
      out.write("              <span>최은서</span>님, 안녕하세요.\r\n");
      out.write("          </dd>\r\n");
      out.write("      </dl>\r\n");
      out.write("      <ul class=\"allInfo\">\r\n");
      out.write("          <li><a href=\"todo.jsp\" class=\"todoIcon\">TO-DO</a></li>\r\n");
      out.write("          <li><a href=\"confirm.jsp\" class=\"confirmIcon\">CONFIRM</a></li>\r\n");
      out.write("          <li class=\"active\"><a href=\"roadmap.jsp\" class=\"roadMapIcon\">ROADMAP</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <dl class=\"headerInner\">\r\n");
      out.write("          <dt>참여중인 프로젝트</dt>\r\n");
      out.write("          <dd class=\"projectSearch\">\r\n");
      out.write("              <input type=\"text\" placeholder=\"프로젝트명을 입력해주세요.\">\r\n");
      out.write("              <input type=\"button\" value=\"\">\r\n");
      out.write("          </dd>\r\n");
      out.write("      </dl>\r\n");
      out.write("      <ul class=\"projectList\">\r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"notice.jsp\" class=\"projectTit\">SAMSUNG 리뉴얼</a>\r\n");
      out.write("          <ul>\r\n");
      out.write("              <li><a href=\"notice.jsp\">TO-DO</a></li>\r\n");
      out.write("              <li><a href=\"notice.jsp\">NOTICE</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("            <a href=\"notice.jsp\" class=\"projectTit\">LG 유지보수</a>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"notice.jsp\">TO-DO</a></li>\r\n");
      out.write("                <li><a href=\"notice.jsp\">NOTICE</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    <section>\r\n");
      out.write("        <dl class=\"conTit\">\r\n");
      out.write("            <dt class=\"conTitM\">공지사항\r\n");
      out.write("                <a href=\"#\" class=\"noticeImg1\">\r\n");
      out.write("                    <img src=\"img/bell.png\" alt=\"\" width=\"24px\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"noticeImg2\">\r\n");
      out.write("                    <img src=\"img/user2.png\" alt=\"\" width=\"19px\">\r\n");
      out.write("                </a>\r\n");
      out.write("            </dt>\r\n");
      out.write("            <dd>오늘의 공지사항을 확인해보세요.</dd>\r\n");
      out.write("        </dl>\r\n");
      out.write("        <div class=\"chatBox\">\r\n");
      out.write("            <dl>\r\n");
      out.write("                <dt>권은영 팀장</dt>\r\n");
      out.write("                <dd class=\"chatBoxCont1\">여러분, 카트 덤비세요~</dd>\r\n");
      out.write("                <dd class=\"chatTime\">오후 11:57</dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("            <dl>\r\n");
      out.write("                <dt>최은서 부사장</dt>\r\n");
      out.write("                <dd class=\"chatBoxCont1\">아니 언니 !!! 코인이나 보내 빨리 ㅡㅡㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇ</dd>\r\n");
      out.write("                <dd class=\"chatTime\">오후 11:59</dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li class=\"chatBoxCont2\">ㄴㅇㅁ라ㅕㅈ마ㅓㅜ</li>\r\n");
      out.write("                <li class=\"chatTime2\">오후 11:59</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li class=\"chatBoxCont2\">ㄴㅁ려ㅑㅗ뮈ㅈ</li>\r\n");
      out.write("                <li class=\"chatTime2\">오후 11:59</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <p>\r\n");
      out.write("                <span>2020년 12월 8일 화요일</span>\r\n");
      out.write("            </p>            \r\n");
      out.write("            <dl>\r\n");
      out.write("                <dt>박실 대리</dt>\r\n");
      out.write("                <dd class=\"chatBoxCont1\">ㅋㅋㅋ</dd>\r\n");
      out.write("                <dd class=\"chatTime\">오전 09:37</dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("            <dl>\r\n");
      out.write("                <dt>곽은진 과장</dt>\r\n");
      out.write("                <dd class=\"chatBoxCont1\">나 속상해 ㅠㅠㅠ</dd>\r\n");
      out.write("                <dd class=\"chatTime\">오전 09:41</dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("            <dl>\r\n");
      out.write("                <dt>원윤희 사원</dt>\r\n");
      out.write("                <dd class=\"chatBoxCont1\">왜그래요 은진씨</dd>\r\n");
      out.write("                <dd class=\"chatTime\">오전 09:43</dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("            <dl>\r\n");
      out.write("                <dt>유영준 인턴</dt>\r\n");
      out.write("                <dd class=\"chatBoxCont1\">설문조사 하겠습니다.</dd>\r\n");
      out.write("                <dd class=\"chatTime\">오전 09:50</dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("            <dl>\r\n");
      out.write("                <dt>유영준 인턴</dt>\r\n");
      out.write("                <dd class=\"chatBoxCont1\">설문조사 완료되면 제 자리에 갖다놔 주세요 반장님 ^^</dd>\r\n");
      out.write("                <dd class=\"chatTime\">오전 09:51</dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("            <dl>\r\n");
      out.write("                <dt>이민형 사원</dt>\r\n");
      out.write("                <dd class=\"chatBoxCont1\">...네</dd>\r\n");
      out.write("                <dd class=\"chatTime\">오전 10:26</dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"chatFoot\">\r\n");
      out.write("            <ul class=\"fileUpload\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <img src=\"img/plus2.png\" alt=\"\" width=\"30px\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"chatSendBox\">\r\n");
      out.write("                    <textarea rows=\"5px\" placeholder=\"메세지를 입력하세요.\"></textarea>\r\n");
      out.write("                    <input type=\"button\" value=\"전송\" class=\"sendBtn\">\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <footer>\r\n");
      out.write("        <ul class=\"quickBar\">\r\n");
      out.write("            <li class=\"members\">\r\n");
      out.write("                <a href=\"#\"><img src=\"img/users.png\" alt=\"\"></a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"chatBtn\">\r\n");
      out.write("                <a href=\"#\"><img src=\"img/chat.png\" alt=\"\"></a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <dl class=\"pop memberCont\">\r\n");
      out.write("        <dt>\r\n");
      out.write("            그룹멤버\r\n");
      out.write("            <a href=\"#\">X</a>\r\n");
      out.write("        </dt>\r\n");
      out.write("        <dd>\r\n");
      out.write("            <div class=\"memberTab\">\r\n");
      out.write("                <ul class=\"tabs\">\r\n");
      out.write("                    <li class=\"active\"><a href=\"#\">전체보기</a></li>\r\n");
      out.write("                    <li><a href=\"#\">멤버초대</a></li>\r\n");
      out.write("                    <li><a href=\"#\">멤버수정</a></li>\r\n");
      out.write("                    <li><a href=\"#\">멤버삭제</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 검색 영역 -->\r\n");
      out.write("            <div class=\"projectSearch search\">\r\n");
      out.write("                <input type=\"text\" placeholder=\"이름, 아이디, 이메일 중 하나를 입력해주세요.\">\r\n");
      out.write("                <input type=\"button\" value=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"tab_content\">\r\n");
      out.write("                <!-- 전체보기 영역 -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <ul class=\"memberTeam\">\r\n");
      out.write("                        <li><a href=\"#\">> 디자인팀</a></li>\r\n");
      out.write("                        <li class=\"memberList\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><img src=\"img/usericon.png\"  alt=\"\">곽은진&nbsp&nbsp&nbsptest.com</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>  \r\n");
      out.write("                    <ul class=\"memberTeam\">\r\n");
      out.write("                        <li><a href=\"#\">> 마케팅팀</a></li>\r\n");
      out.write("                        <li class=\"memberList\">\r\n");
      out.write("                            <ul class=\"memberName\">\r\n");
      out.write("                                <li><img src=\"img/usericon.png\"  alt=\"\">최은서</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>  \r\n");
      out.write("                    <ul class=\"memberTeam\">\r\n");
      out.write("                        <li><a href=\"#\">> 기획팀</a></li>\r\n");
      out.write("                        <li class=\"memberList\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><img src=\"img/usericon.png\"  alt=\"\">권은영</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 멤버검색 영역 -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class=\"table searchMember\">\r\n");
      out.write("                        <table>\r\n");
      out.write("                            <colgroup>\r\n");
      out.write("                                <col width=\"10%\">\r\n");
      out.write("                                <col width=\"40%\"/>\r\n");
      out.write("                                <col width=\"17.5%\"/>\r\n");
      out.write("                                <col width=\"17.5%\"/>\r\n");
      out.write("                                <col width=\"15%\"/>\r\n");
      out.write("                            </colgroup>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th><img src=\"img/usericon.png\"  alt=\"\"></th>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <p>곽은진</p>\r\n");
      out.write("                                    <p class=\"emailTxt\">test@test.com</p>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <select class=\"sel\">\r\n");
      out.write("                                        <option>그룹선택</option>\r\n");
      out.write("                                        <option>마케팅팀</option>\r\n");
      out.write("                                        <option>디자인팀</option>\r\n");
      out.write("                                        <option>기획팀</option>\r\n");
      out.write("                                        <option>재무관리팀</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <select class=\"sel\">\r\n");
      out.write("                                        <option>권한선택</option>\r\n");
      out.write("                                        <option>관리자</option>\r\n");
      out.write("                                        <option>멤버</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>초대<!-- <input type=\"checkbox\"> --></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 멤버수정 영역 -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class=\"table searchMember\">\r\n");
      out.write("                        <table>\r\n");
      out.write("                            <colgroup>\r\n");
      out.write("                                <col width=\"10%\">\r\n");
      out.write("                                <col width=\"40%\"/>\r\n");
      out.write("                                <col width=\"17.5%\"/>\r\n");
      out.write("                                <col width=\"17.5%\"/>\r\n");
      out.write("                                <col width=\"15%\"/>\r\n");
      out.write("                            </colgroup>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th><img src=\"./common/img/usericon.png\"  alt=\"\"></th>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <p>최은서</p>\r\n");
      out.write("                                    <p class=\"emailTxt\">test@test.com</p>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <select class=\"sel\">\r\n");
      out.write("                                        <option>그룹선택</option>\r\n");
      out.write("                                        <option>마케팅팀</option>\r\n");
      out.write("                                        <option>디자인팀</option>\r\n");
      out.write("                                        <option>기획팀</option>\r\n");
      out.write("                                        <option>재무관리팀</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <select class=\"sel\">\r\n");
      out.write("                                        <option>권한선택</option>\r\n");
      out.write("                                        <option>관리자</option>\r\n");
      out.write("                                        <option>멤버</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>수정</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 멤버삭제 영역 -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class=\"table searchMember\">\r\n");
      out.write("                        <table>\r\n");
      out.write("                            <colgroup>\r\n");
      out.write("                                <col width=\"10%\">\r\n");
      out.write("                                <col width=\"40%\"/>\r\n");
      out.write("                                <col width=\"17.5%\"/>\r\n");
      out.write("                                <col width=\"17.5%\"/>\r\n");
      out.write("                                <col width=\"15%\"/>\r\n");
      out.write("                            </colgroup>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th><img src=\"./common/img/usericon.png\"  alt=\"\"></th>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <p>권은영</p>\r\n");
      out.write("                                    <p class=\"emailTxt\">test@test.com</p>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>마케팅팀</td>\r\n");
      out.write("                                <td>관리자</td>\r\n");
      out.write("                                <td>삭제</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </dd>\r\n");
      out.write("    </dl>\r\n");
      out.write("    <div class=\"popupM msgPopup\">\r\n");
      out.write("        <dl>\r\n");
      out.write("            <dt>\r\n");
      out.write("                SAMSUNG 리뉴얼\r\n");
      out.write("                <a href=\"#\" class=\"popupOK\">X</a>\r\n");
      out.write("            </dt>\r\n");
      out.write("        </dl>\r\n");
      out.write("        <ul class=\"msgPopupC\">\r\n");
      out.write("            <li><a href=\"#\">멤버</a></li>\r\n");
      out.write("            <li><a href=\"#\">대화방</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div class=\"projectSearch searchMemberChat\">\r\n");
      out.write("            <input type=\"text\" placeholder=\"멤버를 검색하세요.\">\r\n");
      out.write("            <input type=\"button\" value=\"\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"msgPopupAll\">\r\n");
      out.write("            <div class=\"msgPopupA\">\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">권은영 팀장</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">카트 들어오세요</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">이충진 상무</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">이클립스 끊었습니다.</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">곽은진 과장</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">아 배고파 ㅠㅠㅠ</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">박실 대리</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">아니,, 그니까~~</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">이민형 사원</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">자리비움</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">원윤희 사원</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">다들 말 좀 걸어줘요~</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">유영준 인턴</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">소곤 소곤..</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">유영준 인턴</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">소곤 소곤..</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">유영준 인턴</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">소곤 소곤..</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">유영준 인턴</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">소곤 소곤..</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">유영준 인턴</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">소곤 소곤..</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"msgPopupB\">\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">권은영 팀장, 최은서 부사장, 곽은진 과장</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">카트중...</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">이충진 상무, 박실 대리</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">의왕 단톡방입니다.</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">이민형 사원, 유영준 인턴</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">인턴 정신교육중..</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"popupP chatProfile\">\r\n");
      out.write("        <dl>\r\n");
      out.write("            <dt>\r\n");
      out.write("                프로필\r\n");
      out.write("                <a href=\"#\" class=\"popupOK1\">X</a>\r\n");
      out.write("            </dt>\r\n");
      out.write("            <dd>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <img src=\"./common/img/profile.png\" alt=\"\" width=\"110px\">\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>권은영 팀장</li>\r\n");
      out.write("                    <li>카트 들어오세요</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"btnBox set2\">\r\n");
      out.write("                    <a href=\"#\">1:1 채팅</a>\r\n");
      out.write("                    <a href=\"#\">채팅방 초대</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </dd>\r\n");
      out.write("        </dl>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"darkBack\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
