/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.22
 * Generated at: 2020-10-04 14:12:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class roadmap_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/User/Desktop/IT/3cha/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/3cha(Test3)/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/./common/include/footer.jsp", Long.valueOf(1600867517638L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1600693430257L));
    _jspx_dependants.put("/./common/include/header.jsp", Long.valueOf(1601222234063L));
    _jspx_dependants.put("jar:file:/C:/Users/User/Desktop/IT/3cha/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/3cha(Test3)/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<!-- font-family: 'Montserrat', sans-serif; -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,500i,600,600i,700\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR:100,300,400,500,700,900&subset=korean\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<!-- css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./common/css/reset.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./common/css/common.css\" />\r\n");
      out.write("<!-- js -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"./common/js/common.js\"></script>\r\n");
      out.write("<script src=\"./common/js/work.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./common/css/roadmap.css\">\r\n");
      out.write("<script src=\"./common/js/roadmap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>WithWork</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t/* $(function() {\r\n");
      out.write("\t\t\t$(\".roadmapBtn\").click(function() {\r\n");
      out.write("\t\t\t\tselectCompanyDepart();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tfunction selectCompanyDepart() {\r\n");
      out.write("\t\t\tvar company = $(\"#company option:selected\").val();\r\n");
      out.write("\t\t\tvar depart = $(\"#depart option:selected\").val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax(\"selectCompany.do\",{\r\n");
      out.write("\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\tdata : \"company =\" + company,\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\tvar a = \"\";\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$.each(data, function(){\r\n");
      out.write("\t\t\t\t\t\ta +=\"<select id='company' name='company'>\";\r\n");
      out.write("\t\t\t\t\t\ta +=\"<option>\"+ this.name + \"</option>\";\r\n");
      out.write("\t\t\t\t\t\ta +=\"</select>\";\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t$(\"company\").html(a);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(){\r\n");
      out.write("\t\t\t\t\tconsole.log(\">> selectCompany **Error\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax(\"selectDepart.do\",{\r\n");
      out.write("\t\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\tdata : \"depart =\" + depart,\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar a = \"\";\r\n");
      out.write("\t\t\t\t\t$.each(data, function(){\r\n");
      out.write("\t\t\t\t\t\ta +=\"<div class='roadMapSearch'>\";\r\n");
      out.write("\t\t\t\t\t\ta +=\"<select id='depart' name='depart'>\";\r\n");
      out.write("\t\t\t\t\t\ta +=\"<option>\" + this..depart + \"</option>\";\r\n");
      out.write("\t\t\t\t\t\ta +=\"</select>\";\r\n");
      out.write("\t\t\t\t\t\ta +=\"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"depart\").html(a);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(){\r\n");
      out.write("\t\t\t\t\tconsole.log(\">> selectDepart **Error\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t */\r\n");
      out.write("/*\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\".sendBtnP\").click(function(event) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"/insertProject.do\",\r\n");
      out.write("\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t/* uploadFile : $(\"#uploadFile\").val(), \r\n");
      out.write("\t\t\t\t\t\tp_name : $(\"#p_name\").val(),\r\n");
      out.write("\t\t\t\t\t\tp_content : $(\"#p_content\").val(),\r\n");
      out.write("\t\t\t\t\t\tp_person : $(\"#p_person\").val(),\r\n");
      out.write("\t\t\t\t\t\tp_deadline : $(\"#p_deadline\").val(),\r\n");
      out.write("\t\t\t\t\t\tp_country : $(\"#p_country\").val(),\r\n");
      out.write("\t\t\t\t\t\tp_suzu : $(\"#p_suzu\").val(),\r\n");
      out.write("\t\t\t\t\t\tp_barzu : $(\"#p_barzu\").val(),\r\n");
      out.write("\t\t\t\t\t\tp_total : $(\"#p_total\").val()\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"data :\" + data);\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function() {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"** Error\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t})\r\n");
      out.write("\r\n");
      out.write("\t\t \r\n");
      out.write("\t*/\t \r\n");
      out.write("\t\t $(function(){\r\n");
      out.write("\t\t\t $(\".#sendBtnP\").click(function(){\r\n");
      out.write("\t\t\t\t location.href='insertProject.do';\r\n");
      out.write("\t\t\t });\r\n");
      out.write("\t\t })\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<!-- font-family: 'Montserrat', sans-serif; -->\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,500i,600,600i,700\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR:100,300,400,500,700,900&subset=korean\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("\r\n");
      out.write("    <!-- css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./common/css/reset.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./common/css/common.css\" />\r\n");
      out.write("    <!-- js -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"./common/js/common.js\"></script>\r\n");
      out.write("    <script src=\"./common/js/work.js\"></script>\r\n");
      out.write("<title>WithWork</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<header>\r\n");
      out.write("      <dl class=\"groupInfo headerInner\">\r\n");
      out.write("          <dt>GOOGLE</dt>\r\n");
      out.write("          <dd>\r\n");
      out.write("              <img src=\"./common/img/user.png\" alt=\"\">\r\n");
      out.write("              <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>님, 안녕하세요.\r\n");
      out.write("          </dd>\r\n");
      out.write("      </dl>\r\n");
      out.write("      <ul class=\"allInfo\">\r\n");
      out.write("          <li><a href=\"todo2.jsp\" class=\"todoIcon\">TO-DO</a></li>\r\n");
      out.write("          <li><a href=\"confirm.jsp\" class=\"confirmIcon\">CONFIRM</a></li>\r\n");
      out.write("          <li class=\"active\"><a href=\"roadmap.jsp\" class=\"roadMapIcon\">ROADMAP</a></li>\r\n");
      out.write("          <li><a href=\"project.jsp\" class=\"todoIcon\">PROJECT</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <dl class=\"headerInner\">\r\n");
      out.write("          <dt>참여중인 프로젝트</dt>\r\n");
      out.write("          <dd class=\"projectSearch\">\r\n");
      out.write("              <input type=\"text\" placeholder=\"프로젝트명을 입력해주세요.\">\r\n");
      out.write("              <input type=\"button\" value=\"\">\r\n");
      out.write("          </dd>\r\n");
      out.write("      </dl>\r\n");
      out.write("      <ul class=\"projectList\">\r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"notice.jsp\" class=\"projectTit\">SAMSUNG 리뉴얼</a>\r\n");
      out.write("          <ul>\r\n");
      out.write("              <li><a href=\"notice.jsp\">TO-DO</a></li>\r\n");
      out.write("              <li><a href=\"notice.jsp\">NOTICE</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("            <a href=\"notice.jsp\" class=\"projectTit\">LG 유지보수</a>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"notice.jsp\">TO-DO</a></li>\r\n");
      out.write("                <li><a href=\"notice.jsp\">NOTICE</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- -------------------------------- -->\r\n");
      out.write("\t<section>\r\n");
      out.write("\t<dl class=\"conTit\">\r\n");
      out.write("\t\t<dt>ROADMAP</dt>\r\n");
      out.write("\t\t<dd>현재 회사에서 진행 또는 심사 중인 프로젝트를 확인해보세요.</dd>\r\n");
      out.write("\t</dl>\r\n");
      out.write("\t<div class=\"roadMapTab\">\r\n");
      out.write("\t\t<ul class=\"roadMapNav\">\r\n");
      out.write("\t\t\t<li class=\"active\"><a href=\"#\">전체일정</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">스케줄러</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<div class=\"roadMapCont\">\r\n");
      out.write("\t\t\t<div class=\"progress\" style=\"display: block;\">\r\n");
      out.write("\t\t\t\t<form action=\"selectCompanyDepart.do\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<div class=\"roadMapSearch\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<select id=\"company\" name=\"company\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select> <select id=\"depart\" name=\"depart\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select> <input type=\"text\" name=\"searchRoadmap\"> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"button\" value=\"검색\" class='roadmapBtn'>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<div class=\"roadMapState smallMG\">\r\n");
      out.write("\t\t\t\t\t<dl class=\"stateForm\">\r\n");
      out.write("\t\t\t\t\t\t<dt class=\"waiting\" name=\"p_stat\">검토 중</dt>\r\n");
      out.write("\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<dl class=\"projectThumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<dt>LINE</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<dd>AI/인공지능 프로젝트</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<dd>Lorem ipsum dolor sit, amet consectetur adipisicing\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\telit. Culpa quaerat quisquam magni aperiam minima quam, dicta\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsequi. Vel, consectetur totam.</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</dd>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t<dl class=\"stateForm\">\r\n");
      out.write("\t\t\t\t\t\t<dt class=\"starting\" name=\"p_stat\">진행 중</dt>\r\n");
      out.write("\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<dl class=\"projectThumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<dt>LINE</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<dd>AI/인공지능 프로젝트</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<dd>Lorem ipsum dolor sit, amet consectetur adipisicing\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\telit. Culpa quaerat quisquam magni aperiam minima quam, dicta\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsequi. Vel, consectetur totam.</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</dd>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t<dl class=\"stateForm\">\r\n");
      out.write("\t\t\t\t\t\t<dt class=\"stopping\" name=\"p_stat\">승인대기 중</dt>\r\n");
      out.write("\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<dl class=\"projectThumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<dt>LINE</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<dd>AI/인공지능 프로젝트</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<dd>Lorem ipsum dolor sit, amet consectetur adipisicing\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\telit. Culpa quaerat quisquam magni aperiam minima quam, dicta\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsequi. Vel, consectetur totam.</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</dd>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<table class=\"scriptCalendar smallMG\">\r\n");
      out.write("\t\t\t\t\t<caption>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" onClick=\"prevCalendar();\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"./common/img/prev.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t</a> <span id=\"calYear\">YYYY</span>. <span id=\"calMonth\">MM</span> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#\" onClick=\"nextCalendar();\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"./common/img/next.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</caption>\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>SUN</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>MON</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>TUE</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>WED</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>THU</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>FRI</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>SAT</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody></tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- ------footer----- -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write(" <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,500i,600,600i,700\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR:100,300,400,500,700,900&subset=korean\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("\r\n");
      out.write("    <!-- css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./common/css/reset.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./common/css/common.css\" />\r\n");
      out.write("\t <!-- js -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"./common/js/common.js\"></script>\r\n");
      out.write("    <script src=\"./common/js/work.js\"></script>\r\n");
      out.write("<title>팝업</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<footer>\r\n");
      out.write("      <ul class=\"quickBar\">\r\n");
      out.write("          <li class=\"members\">\r\n");
      out.write("              <a href=\"#\"><img src=\"./common/img/users.png\" alt=\"\"></a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"chatBtn\">\r\n");
      out.write("              <a href=\"#\"><img src=\"./common/img/chat.png\" alt=\"\"></a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"projectBtn\">\r\n");
      out.write("              <a href=\"#\"><img src=\"./common/img/department.png\" alt=\"\"></a>\r\n");
      out.write("          </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <dl class=\"pop memberCont\">\r\n");
      out.write("      <dt>\r\n");
      out.write("          그룹멤버\r\n");
      out.write("          <a href=\"#\">X</a>\r\n");
      out.write("      </dt>\r\n");
      out.write("      <dd>\r\n");
      out.write("          <div class=\"memberTab\">\r\n");
      out.write("              <ul class=\"tabs\">\r\n");
      out.write("                  <li class=\"active\"><a href=\"#\">전체보기</a></li>\r\n");
      out.write("                  <li><a href=\"#\">멤버초대</a></li>\r\n");
      out.write("                  <li><a href=\"#\">멤버수정</a></li>\r\n");
      out.write("                  <li><a href=\"#\">멤버삭제</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- 검색 영역 -->\r\n");
      out.write("          <div class=\"projectSearch search\">\r\n");
      out.write("              <input type=\"text\" placeholder=\"이름, 아이디, 이메일 중 하나를 입력해주세요.\">\r\n");
      out.write("              <input type=\"button\" value=\"\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"tab_content\">\r\n");
      out.write("              <!-- 전체보기 영역 -->\r\n");
      out.write("              <div>\r\n");
      out.write("                  <ul class=\"memberTeam\">\r\n");
      out.write("                      <li><a href=\"#\">> 디자인팀</a></li>\r\n");
      out.write("                      <li class=\"memberList\">\r\n");
      out.write("                          <ul>\r\n");
      out.write("                              <li><img src=\"./common/img/usericon.png\"  alt=\"\">곽은진&nbsp&nbsp&nbsptest.com</li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                      </li>\r\n");
      out.write("                  </ul>  \r\n");
      out.write("                  <ul class=\"memberTeam\">\r\n");
      out.write("                      <li><a href=\"#\">> 마케팅팀</a></li>\r\n");
      out.write("                      <li class=\"memberList\">\r\n");
      out.write("                          <ul class=\"memberName\">\r\n");
      out.write("                              <li><img src=\"./common/img/usericon.png\"  alt=\"\">최은서</li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                      </li>\r\n");
      out.write("                  </ul>  \r\n");
      out.write("                  <ul class=\"memberTeam\">\r\n");
      out.write("                      <li><a href=\"#\">> 기획팀</a></li>\r\n");
      out.write("                      <li class=\"memberList\">\r\n");
      out.write("                          <ul>\r\n");
      out.write("                              <li><img src=\"./common/img/usericon.png\"  alt=\"\">권은영</li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                      </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- 멤버검색 영역 -->\r\n");
      out.write("              <div>\r\n");
      out.write("                  <div class=\"table searchMember\">\r\n");
      out.write("                      <table>\r\n");
      out.write("                          <colgroup>\r\n");
      out.write("                              <col width=\"10%\">\r\n");
      out.write("                              <col width=\"40%\"/>\r\n");
      out.write("                              <col width=\"17.5%\"/>\r\n");
      out.write("                              <col width=\"17.5%\"/>\r\n");
      out.write("                              <col width=\"15%\"/>\r\n");
      out.write("                          </colgroup>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                              <th><img src=\"./common/img/usericon.png\"  alt=\"\"></th>\r\n");
      out.write("                              <td>\r\n");
      out.write("                                  <p>곽은진</p>\r\n");
      out.write("                                  <p class=\"emailTxt\">test@test.com</p>\r\n");
      out.write("                              </td>\r\n");
      out.write("                              <td>\r\n");
      out.write("                                  <select class=\"sel\">\r\n");
      out.write("                                      <option>그룹선택</option>\r\n");
      out.write("                                      <option>마케팅팀</option>\r\n");
      out.write("                                      <option>디자인팀</option>\r\n");
      out.write("                                      <option>기획팀</option>\r\n");
      out.write("                                      <option>재무관리팀</option>\r\n");
      out.write("                                  </select>\r\n");
      out.write("                              </td>\r\n");
      out.write("                              <td>\r\n");
      out.write("                                  <select class=\"sel\">\r\n");
      out.write("                                      <option>권한선택</option>\r\n");
      out.write("                                      <option>관리자</option>\r\n");
      out.write("                                      <option>멤버</option>\r\n");
      out.write("                                  </select>\r\n");
      out.write("                              </td>\r\n");
      out.write("                              <td>초대<!-- <input type=\"checkbox\"> --></td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                      </table>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- 멤버수정 영역 -->\r\n");
      out.write("              <div>\r\n");
      out.write("                  <div class=\"table searchMember\">\r\n");
      out.write("                      <table>\r\n");
      out.write("                          <colgroup>\r\n");
      out.write("                              <col width=\"10%\">\r\n");
      out.write("                              <col width=\"40%\"/>\r\n");
      out.write("                              <col width=\"17.5%\"/>\r\n");
      out.write("                              <col width=\"17.5%\"/>\r\n");
      out.write("                              <col width=\"15%\"/>\r\n");
      out.write("                          </colgroup>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                              <th><img src=\"./common/img/usericon.png\"  alt=\"\"></th>\r\n");
      out.write("                              <td>\r\n");
      out.write("                                  <p>최은서</p>\r\n");
      out.write("                                  <p class=\"emailTxt\">test@test.com</p>\r\n");
      out.write("                              </td>\r\n");
      out.write("                              <td>\r\n");
      out.write("                                  <select class=\"sel\">\r\n");
      out.write("                                      <option>그룹선택</option>\r\n");
      out.write("                                      <option>마케팅팀</option>\r\n");
      out.write("                                      <option>디자인팀</option>\r\n");
      out.write("                                      <option>기획팀</option>\r\n");
      out.write("                                      <option>재무관리팀</option>\r\n");
      out.write("                                  </select>\r\n");
      out.write("                              </td>\r\n");
      out.write("                              <td>\r\n");
      out.write("                                  <select class=\"sel\">\r\n");
      out.write("                                      <option>권한선택</option>\r\n");
      out.write("                                      <option>관리자</option>\r\n");
      out.write("                                      <option>멤버</option>\r\n");
      out.write("                                  </select>\r\n");
      out.write("                              </td>\r\n");
      out.write("                              <td>수정</td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                      </table>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- 멤버삭제 영역 -->\r\n");
      out.write("              <div>\r\n");
      out.write("                  <div class=\"table searchMember\">\r\n");
      out.write("                      <table>\r\n");
      out.write("                          <colgroup>\r\n");
      out.write("                              <col width=\"10%\">\r\n");
      out.write("                              <col width=\"40%\"/>\r\n");
      out.write("                              <col width=\"17.5%\"/>\r\n");
      out.write("                              <col width=\"17.5%\"/>\r\n");
      out.write("                              <col width=\"15%\"/>\r\n");
      out.write("                          </colgroup>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                              <th><img src=\"./common/img/usericon.png\"  alt=\"\"></th>\r\n");
      out.write("                              <td>\r\n");
      out.write("                                  <p>권은영</p>\r\n");
      out.write("                                  <p class=\"emailTxt\">test@test.com</p>\r\n");
      out.write("                              </td>\r\n");
      out.write("                              <td>마케팅팀</td>\r\n");
      out.write("                              <td>관리자</td>\r\n");
      out.write("                              <td>삭제</td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                      </table>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("      </dd>\r\n");
      out.write("    </dl>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- ------프로젝트 팝업 팝업 popup ------ -->\r\n");
      out.write("\t<div class=\"popupP roadmapPopup\">\r\n");
      out.write("\t\t<dl>\r\n");
      out.write("\t\t\t<dt>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t프로젝트 검토중 <a href=\"#\" class=\"popupOK1\">X</a>\r\n");
      out.write("\t\t\t</dt>\r\n");
      out.write("\t\t\t<dd>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><img src=\"./common/img/profile.png\" alt=\"\" width=\"110px\">\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>권은영부장</li>\r\n");
      out.write("\t\t\t\t\t<li>담당자</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<div class=\"btnBox set2\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">상세보기</a> <a href=\"#\">문의하기</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</dd>\r\n");
      out.write("\t\t</dl>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- -----상세 내역 팝업 ------ -->\r\n");
      out.write("\t<div class=\"popupP roadmapPopup\">\r\n");
      out.write("\t\t<dl>\r\n");
      out.write("\t\t\t<dt>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t프로젝트 검토중 <a href=\"#\" class=\"popupOK1\">X</a>\r\n");
      out.write("\t\t\t</dt>\r\n");
      out.write("\t\t\t<dd>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><img src=\"./common/img/profile.png\" alt=\"\" width=\"110px\">\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>권은영부장</li>\r\n");
      out.write("\t\t\t\t\t<li>담당자</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<div class=\"btnBox set2\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" id=\"messRoad\">상세보기</a> <a href=\"#\">문의하기</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</dd>\r\n");
      out.write("\t\t</dl>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- ----프로젝트 정보 팝업---- -->\r\n");
      out.write("\t<div class=\"popup roadmapInfoPopup\">\r\n");
      out.write("\t\t<dl>\r\n");
      out.write("\t\t\t<dt>상태(점검, 진행, 최종검토)</dt>\r\n");
      out.write("\t\t\t<dd>\r\n");
      out.write("\t\t\t\t<div class=\"table workDetail\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"15%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"30%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"15%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"30%\">\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>프로젝트명</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\">라인</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>프로젝트내용</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\">AI 음성인식 프로젝트</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>수주회사</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>라인</td>\r\n");
      out.write("\t\t\t\t\t\t\t<th>발주회사</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>디지토피아</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>인력구성</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\">개발2, 디자인1, 기획1, 퍼블리셔1.</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>예상예산</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\">60,000,000</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"btnBox\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"popupOK\">확인</a> &nbsp; &nbsp; <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"popupBACK\">뒤로가기</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</dd>\r\n");
      out.write("\t\t</dl>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"darkBack\"></div>\r\n");
      out.write("\t<!-- ------- 프로젝트 생성 팝업 -------- -->\r\n");
      out.write("\t<form action=\"insertProject.do\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t<div class=\"popup projectAddPopup\">\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t프로젝트 생성 <a href=\"#\" class=\"popupOK\">X</a>\r\n");
      out.write("\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<div class=\"table workDetail\">\r\n");
      out.write("\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"15%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"30%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"15%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"30%\">\r\n");
      out.write("\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>서류제출</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <td colspan=\"3\"><input type=\"file\" name=\"uploadFile\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t -->\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>프로젝트명</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\" style=\"width: 100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"p_name\" id=\"p_name\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>내용</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\" style=\"width: 100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"p_content\" id=\"p_content\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>담당자</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>인력구성</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\" style=\"width: 100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"p_person\" id=\"p_person\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>수주</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"1\"><input type=\"text\" style=\"width: 100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"p_suzu\" id=\"p_suzu\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>발주</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"1\"><input type=\"text\" style=\"width: 100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"p_barzu\" id=\"p_barzu\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>예상기한</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"1\"><input type=\"text\" style=\"width: 100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"p_deadline\" id=\"p_deadline\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>국내/해외</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"1\"><input type=\"checkbox\" name=\"p_country\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"p_country\" value=\"국내\">국내 <input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"p_country\" id=\"p_country\" value=\"해외\" checked=\"checked\">해외</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>총예상금액</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\" style=\"width: 100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"p_total\" id=\"p_total\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"btnBox\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" id=\"sendBtnP\" class=\"popupOK\" value=\"생성\"> &nbsp;<a href=\"#\">취소</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<div class=\"darkBack\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /roadmap.jsp(171,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/roadmap.jsp(171,7) '${companyList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${companyList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /roadmap.jsp(171,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("companyList");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t<option>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${companyList.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
