/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.22
 * Generated at: 2020-10-01 11:58:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class roadmap_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/./common/include/footer.jsp", Long.valueOf(1600867517638L));
    _jspx_dependants.put("jar:file:/C:/Users/User/Desktop/IT/3cha/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/3cha(Test)/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1600693430257L));
    _jspx_dependants.put("/./common/include/header.jsp", Long.valueOf(1601222234063L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<!-- font-family: 'Montserrat', sans-serif; -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,500i,600,600i,700\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR:100,300,400,500,700,900&subset=korean\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<!-- css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./common/css/reset.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./common/css/common.css\" />\r\n");
      out.write("<!-- js -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"./common/js/common.js\"></script>\r\n");
      out.write("<script src=\"./common/js/work.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./common/css/roadmap.css\">\r\n");
      out.write("<script src=\"./common/js/roadmap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>WithWork</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$(\"#sendBtn\").click(function(){\r\n");
      out.write("\t\t\t\tinsertProject();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction insertProject(){\r\n");
      out.write("\t\t\tvar projectCreate = [\r\n");
      out.write("\t\t\t\t\"filetrans\" : $(\".filetrans\").val(),\r\n");
      out.write("\t\t\t\t\"projectname\" : $(\".projectname\").val(),\r\n");
      out.write("\t\t\t\t\"projectcontent\" : $(\".projectcontent\").val(),\r\n");
      out.write("\t\t\t\t\"projectperson\" : $(\".projectperson\").val(),\r\n");
      out.write("\t\t\t\t\"projectsuzu\" : $(\".projectsuzu\").val(),\r\n");
      out.write("\t\t\t\t\"projectbarzu\" : $(\".projectbarzu\").val(),\r\n");
      out.write("\t\t\t\t\"projectdealine\" : $(\".projectdealine\").val(),\r\n");
      out.write("\t\t\t\t\"projectcountry\" : $(\".projectcountry\").val(),\r\n");
      out.write("\t\t\t\t\"projectinput\" : $(\".projectinput\").val();\r\n");
      out.write("\t\t\t];\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax(\"insertProject.do\" ,{\r\n");
      out.write("\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\tdata : \"projectCreate\", \r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\talert(\"data : \" + data);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(){\r\n");
      out.write("\t\t\t\t\talert(\"삽입에러\")\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- \t<script>\r\n");
      out.write("\t\t$(\r\n");
      out.write("\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\tbuttonEvent();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tfunction buttonEvent() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t$(\"button\")\r\n");
      out.write("\t\t\t\t\t\t\t\t.click(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar num = $(this).attr(\"p_num\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar stat = $(this).attr(\"p_stat\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\turl : \"updateRoadmap.do\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tp_num : p_num,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tp_stat : p_stat\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\".waiting\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.html(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"<dl><dt>검토중</dl></dt>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\".starting\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.html(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"<dl><dt>진행중</dl></dt>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\".stopping\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.html(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"<dl><dt>최종승인대기중</dl></dt>\")\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfor (var i = 0; i < data.length; i++) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar result = \"\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tif (data[i].type == 'waiting') {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += '<dl class=\"projectThumb\">';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += '<dt>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ data[i].c_name\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '</dt>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += '<dd>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ data[i].p_name\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '</dd>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += '<dd>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ data[i].p_content\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '</dd>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += '</dl>';\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\".roadMapState smallMG\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.append(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t} else if (data[i].type = 'starting') {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += '<dl class=\"projectThumb\">';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += '<dt>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ data[i].c_name\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '</dt>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += '<dd>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ data[i].p_name\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '</dd>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += '<dd>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ data[i].p_content\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '</dd>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += '</dl>';\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\".roadMapState smallMG\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.append(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += '<dl class=\"projectThumb\">';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += '<dt>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ data[i].c_name\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '</dt>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += '<dd>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ data[i].p_name\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '</dd>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += '<dd>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ data[i].p_content\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '</dd>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += '</dl>';\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"roadMapState smallMG\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.append(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tbuttonEvent();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t</script> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<!-- font-family: 'Montserrat', sans-serif; -->\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,500i,600,600i,700\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR:100,300,400,500,700,900&subset=korean\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("\r\n");
      out.write("    <!-- css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./common/css/reset.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./common/css/common.css\" />\r\n");
      out.write("    <!-- js -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"./common/js/common.js\"></script>\r\n");
      out.write("    <script src=\"./common/js/work.js\"></script>\r\n");
      out.write("<title>WithWork</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<header>\r\n");
      out.write("      <dl class=\"groupInfo headerInner\">\r\n");
      out.write("          <dt>GOOGLE</dt>\r\n");
      out.write("          <dd>\r\n");
      out.write("              <img src=\"./common/img/user.png\" alt=\"\">\r\n");
      out.write("              <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>님, 안녕하세요.\r\n");
      out.write("          </dd>\r\n");
      out.write("      </dl>\r\n");
      out.write("      <ul class=\"allInfo\">\r\n");
      out.write("          <li><a href=\"todo2.jsp\" class=\"todoIcon\">TO-DO</a></li>\r\n");
      out.write("          <li><a href=\"confirm.jsp\" class=\"confirmIcon\">CONFIRM</a></li>\r\n");
      out.write("          <li class=\"active\"><a href=\"roadmap.jsp\" class=\"roadMapIcon\">ROADMAP</a></li>\r\n");
      out.write("          <li><a href=\"project.jsp\" class=\"todoIcon\">PROJECT</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <dl class=\"headerInner\">\r\n");
      out.write("          <dt>참여중인 프로젝트</dt>\r\n");
      out.write("          <dd class=\"projectSearch\">\r\n");
      out.write("              <input type=\"text\" placeholder=\"프로젝트명을 입력해주세요.\">\r\n");
      out.write("              <input type=\"button\" value=\"\">\r\n");
      out.write("          </dd>\r\n");
      out.write("      </dl>\r\n");
      out.write("      <ul class=\"projectList\">\r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"notice.jsp\" class=\"projectTit\">SAMSUNG 리뉴얼</a>\r\n");
      out.write("          <ul>\r\n");
      out.write("              <li><a href=\"notice.jsp\">TO-DO</a></li>\r\n");
      out.write("              <li><a href=\"notice.jsp\">NOTICE</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("            <a href=\"notice.jsp\" class=\"projectTit\">LG 유지보수</a>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"notice.jsp\">TO-DO</a></li>\r\n");
      out.write("                <li><a href=\"notice.jsp\">NOTICE</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- -------------------------------- -->\r\n");
      out.write("\t<section>\r\n");
      out.write("\t<dl class=\"conTit\">\r\n");
      out.write("\t\t<dt>ROADMAP</dt>\r\n");
      out.write("\t\t<dd>현재 회사에서 진행 또는 심사 중인 프로젝트를 확인해보세요.</dd>\r\n");
      out.write("\t</dl>\r\n");
      out.write("\t<div class=\"roadMapTab\">\r\n");
      out.write("\t\t<ul class=\"roadMapNav\">\r\n");
      out.write("\t\t\t<li class=\"active\"><a href=\"#\">전체일정</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">스케줄러</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<div class=\"roadMapCont\">\r\n");
      out.write("\t\t\t<div class=\"progress\" style=\"display: block;\">\r\n");
      out.write("\t\t\t\t<form action=\"getRoadmapList.do\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<div class=\"roadMapSearch\">\r\n");
      out.write("\t\t\t\t\t\t<select name=\"searchCompany\">\r\n");
      out.write("\t\t\t\t\t\t\t<option>카카오</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>우아한형제들</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>라인</option>\r\n");
      out.write("\t\t\t\t\t\t</select> <select name=\"searchDepart\">\r\n");
      out.write("\t\t\t\t\t\t\t<option>디자인</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>개발</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>경영</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>인사</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>마케팅</option>\r\n");
      out.write("\t\t\t\t\t\t</select> <input type=\"text\" name=\"searchKeyword\"> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"submit\" value=\"검색\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- ------------- Roadmap main ---------------- -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<table class=\"scriptCalendar smallMG\">\r\n");
      out.write("\t\t\t\t\t<caption>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" onClick=\"prevCalendar();\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"./common/img/prev.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t</a> <span id=\"calYear\">YYYY</span>. <span id=\"calMonth\">MM</span> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#\" onClick=\"nextCalendar();\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"./common/img/next.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</caption>\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>SUN</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>MON</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>TUE</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>WED</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>THU</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>FRI</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>SAT</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody></tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- ------footer----- -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write(" <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,500i,600,600i,700\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR:100,300,400,500,700,900&subset=korean\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("\r\n");
      out.write("    <!-- css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./common/css/reset.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./common/css/common.css\" />\r\n");
      out.write("\t <!-- js -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"./common/js/common.js\"></script>\r\n");
      out.write("    <script src=\"./common/js/work.js\"></script>\r\n");
      out.write("<title>팝업</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<footer>\r\n");
      out.write("      <ul class=\"quickBar\">\r\n");
      out.write("          <li class=\"members\">\r\n");
      out.write("              <a href=\"#\"><img src=\"./common/img/users.png\" alt=\"\"></a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"chatBtn\">\r\n");
      out.write("              <a href=\"#\"><img src=\"./common/img/chat.png\" alt=\"\"></a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"projectBtn\">\r\n");
      out.write("              <a href=\"#\"><img src=\"./common/img/department.png\" alt=\"\"></a>\r\n");
      out.write("          </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <dl class=\"pop memberCont\">\r\n");
      out.write("      <dt>\r\n");
      out.write("          그룹멤버\r\n");
      out.write("          <a href=\"#\">X</a>\r\n");
      out.write("      </dt>\r\n");
      out.write("      <dd>\r\n");
      out.write("          <div class=\"memberTab\">\r\n");
      out.write("              <ul class=\"tabs\">\r\n");
      out.write("                  <li class=\"active\"><a href=\"#\">전체보기</a></li>\r\n");
      out.write("                  <li><a href=\"#\">멤버초대</a></li>\r\n");
      out.write("                  <li><a href=\"#\">멤버수정</a></li>\r\n");
      out.write("                  <li><a href=\"#\">멤버삭제</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- 검색 영역 -->\r\n");
      out.write("          <div class=\"projectSearch search\">\r\n");
      out.write("              <input type=\"text\" placeholder=\"이름, 아이디, 이메일 중 하나를 입력해주세요.\">\r\n");
      out.write("              <input type=\"button\" value=\"\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"tab_content\">\r\n");
      out.write("              <!-- 전체보기 영역 -->\r\n");
      out.write("              <div>\r\n");
      out.write("                  <ul class=\"memberTeam\">\r\n");
      out.write("                      <li><a href=\"#\">> 디자인팀</a></li>\r\n");
      out.write("                      <li class=\"memberList\">\r\n");
      out.write("                          <ul>\r\n");
      out.write("                              <li><img src=\"./common/img/usericon.png\"  alt=\"\">곽은진&nbsp&nbsp&nbsptest.com</li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                      </li>\r\n");
      out.write("                  </ul>  \r\n");
      out.write("                  <ul class=\"memberTeam\">\r\n");
      out.write("                      <li><a href=\"#\">> 마케팅팀</a></li>\r\n");
      out.write("                      <li class=\"memberList\">\r\n");
      out.write("                          <ul class=\"memberName\">\r\n");
      out.write("                              <li><img src=\"./common/img/usericon.png\"  alt=\"\">최은서</li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                      </li>\r\n");
      out.write("                  </ul>  \r\n");
      out.write("                  <ul class=\"memberTeam\">\r\n");
      out.write("                      <li><a href=\"#\">> 기획팀</a></li>\r\n");
      out.write("                      <li class=\"memberList\">\r\n");
      out.write("                          <ul>\r\n");
      out.write("                              <li><img src=\"./common/img/usericon.png\"  alt=\"\">권은영</li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                      </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- 멤버검색 영역 -->\r\n");
      out.write("              <div>\r\n");
      out.write("                  <div class=\"table searchMember\">\r\n");
      out.write("                      <table>\r\n");
      out.write("                          <colgroup>\r\n");
      out.write("                              <col width=\"10%\">\r\n");
      out.write("                              <col width=\"40%\"/>\r\n");
      out.write("                              <col width=\"17.5%\"/>\r\n");
      out.write("                              <col width=\"17.5%\"/>\r\n");
      out.write("                              <col width=\"15%\"/>\r\n");
      out.write("                          </colgroup>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                              <th><img src=\"./common/img/usericon.png\"  alt=\"\"></th>\r\n");
      out.write("                              <td>\r\n");
      out.write("                                  <p>곽은진</p>\r\n");
      out.write("                                  <p class=\"emailTxt\">test@test.com</p>\r\n");
      out.write("                              </td>\r\n");
      out.write("                              <td>\r\n");
      out.write("                                  <select class=\"sel\">\r\n");
      out.write("                                      <option>그룹선택</option>\r\n");
      out.write("                                      <option>마케팅팀</option>\r\n");
      out.write("                                      <option>디자인팀</option>\r\n");
      out.write("                                      <option>기획팀</option>\r\n");
      out.write("                                      <option>재무관리팀</option>\r\n");
      out.write("                                  </select>\r\n");
      out.write("                              </td>\r\n");
      out.write("                              <td>\r\n");
      out.write("                                  <select class=\"sel\">\r\n");
      out.write("                                      <option>권한선택</option>\r\n");
      out.write("                                      <option>관리자</option>\r\n");
      out.write("                                      <option>멤버</option>\r\n");
      out.write("                                  </select>\r\n");
      out.write("                              </td>\r\n");
      out.write("                              <td>초대<!-- <input type=\"checkbox\"> --></td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                      </table>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- 멤버수정 영역 -->\r\n");
      out.write("              <div>\r\n");
      out.write("                  <div class=\"table searchMember\">\r\n");
      out.write("                      <table>\r\n");
      out.write("                          <colgroup>\r\n");
      out.write("                              <col width=\"10%\">\r\n");
      out.write("                              <col width=\"40%\"/>\r\n");
      out.write("                              <col width=\"17.5%\"/>\r\n");
      out.write("                              <col width=\"17.5%\"/>\r\n");
      out.write("                              <col width=\"15%\"/>\r\n");
      out.write("                          </colgroup>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                              <th><img src=\"./common/img/usericon.png\"  alt=\"\"></th>\r\n");
      out.write("                              <td>\r\n");
      out.write("                                  <p>최은서</p>\r\n");
      out.write("                                  <p class=\"emailTxt\">test@test.com</p>\r\n");
      out.write("                              </td>\r\n");
      out.write("                              <td>\r\n");
      out.write("                                  <select class=\"sel\">\r\n");
      out.write("                                      <option>그룹선택</option>\r\n");
      out.write("                                      <option>마케팅팀</option>\r\n");
      out.write("                                      <option>디자인팀</option>\r\n");
      out.write("                                      <option>기획팀</option>\r\n");
      out.write("                                      <option>재무관리팀</option>\r\n");
      out.write("                                  </select>\r\n");
      out.write("                              </td>\r\n");
      out.write("                              <td>\r\n");
      out.write("                                  <select class=\"sel\">\r\n");
      out.write("                                      <option>권한선택</option>\r\n");
      out.write("                                      <option>관리자</option>\r\n");
      out.write("                                      <option>멤버</option>\r\n");
      out.write("                                  </select>\r\n");
      out.write("                              </td>\r\n");
      out.write("                              <td>수정</td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                      </table>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- 멤버삭제 영역 -->\r\n");
      out.write("              <div>\r\n");
      out.write("                  <div class=\"table searchMember\">\r\n");
      out.write("                      <table>\r\n");
      out.write("                          <colgroup>\r\n");
      out.write("                              <col width=\"10%\">\r\n");
      out.write("                              <col width=\"40%\"/>\r\n");
      out.write("                              <col width=\"17.5%\"/>\r\n");
      out.write("                              <col width=\"17.5%\"/>\r\n");
      out.write("                              <col width=\"15%\"/>\r\n");
      out.write("                          </colgroup>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                              <th><img src=\"./common/img/usericon.png\"  alt=\"\"></th>\r\n");
      out.write("                              <td>\r\n");
      out.write("                                  <p>권은영</p>\r\n");
      out.write("                                  <p class=\"emailTxt\">test@test.com</p>\r\n");
      out.write("                              </td>\r\n");
      out.write("                              <td>마케팅팀</td>\r\n");
      out.write("                              <td>관리자</td>\r\n");
      out.write("                              <td>삭제</td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                      </table>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("      </dd>\r\n");
      out.write("    </dl>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- -----상세 내역 팝업 ------ -->\r\n");
      out.write("\t<div class=\"popupP roadmapPopup\">\r\n");
      out.write("\t\t<dl>\r\n");
      out.write("\t\t\t<dt>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t프로젝트 검토중 <a href=\"#\" class=\"popupOK1\">X</a>\r\n");
      out.write("\t\t\t</dt>\r\n");
      out.write("\t\t\t<dd>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><img src=\"./common/img/profile.png\" alt=\"\" width=\"110px\">\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>권은영부장</li>\r\n");
      out.write("\t\t\t\t\t<li>담당자</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<div class=\"btnBox set2\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" id=\"messRoad\">상세보기</a> <a href=\"#\">문의하기</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</dd>\r\n");
      out.write("\t\t</dl>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- ----프로젝트 정보 팝업---- -->\r\n");
      out.write("\t<div class=\"popup roadmapInfoPopup\">\r\n");
      out.write("\t\t<dl>\r\n");
      out.write("\t\t\t<dt></dt>\r\n");
      out.write("\t\t\t<dd>\r\n");
      out.write("\t\t\t\t<div class=\"table workDetail\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"15%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"30%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"15%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"30%\">\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>프로젝트명</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\">라인</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>프로젝트내용</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\">AI 음성인식 프로젝트</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>수주회사</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>라인</td>\r\n");
      out.write("\t\t\t\t\t\t\t<th>발주회사</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>디지토피아</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>인력구성</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\">개발2, 디자인1, 기획1, 퍼블리셔1.</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>예상예산</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\">60,000,000</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"btnBox\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"popupOK\">확인</a> &nbsp; &nbsp; <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"popupBACK\">뒤로가기</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</dd>\r\n");
      out.write("\t\t</dl>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"darkBack\"></div>\r\n");
      out.write("\t<!-- ------- 프로젝트 생성 팝업 -------- -->\r\n");
      out.write("\t<form action=\"projectInsert.do\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t<div class=\"popup projectAddPopup\">\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t프로젝트 생성 <a href=\"#\" class=\"popupOK\">X</a>\r\n");
      out.write("\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<div class=\"table workDetail\">\r\n");
      out.write("\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"15%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"30%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"15%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"30%\">\r\n");
      out.write("\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>서류제출</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"file\" name=\"uploadFile\" class=\"filetrans\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>프로젝트명</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\" style=\"width: 100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"p_name\" class=\"projectname\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>내용</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\" style=\"width: 100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"p_content\" class=\"projectcontent\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>담당자</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\" style=\"width: 100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>투입인력</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\" style=\"width: 100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"p_person\" class=\"projectperson\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>수주</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"1\"><input type=\"text\" style=\"width: 100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"p_suzu\" class=\"projectsuzu\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>발주</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"1\"><input type=\"text\" style=\"width: 100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"p_barzu\" class=\"projectbarzu\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>예상기한</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"1\"><input type=\"text\" style=\"width: 100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"p_total\" class=\"projectdealine\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>국내/해외</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"1\"><input type=\"checkbox\" name=\"chk_info\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"국내\" name=\"p_country\" class=\"projectcountry\">국내 <input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"chk_info\" value=\"해외\" checked=\"checked\" name=\"p_country\" class=\"projectcountry\">해외\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>투입금액</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\" style=\"width: 100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"p_total\" class=\"projectinput\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"btnBox\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" id=\"sendBtn\" class=\"popupOK\" value=\"생성\"> <a href=\"#\">취소</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<div class=\"darkBack\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
